app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),   
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
     path('user/', include('users.urls', namespace='user'))
]

if settings.DEBUG:
    urlpatterns += [
    path("__debug__/", include("debug_toolbar.urls")),  
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import include, path
# from .views import booking
# from .views import update_booking
from goods import views

app_name='goods'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),
    # path('booking/<int:product_id>/', booking, name='booking'),
    # path('booking/update/<int:display_id>/', update_booking, name='update_booking'),
    # path('update-booking/', update_booking, name='update_booking_url'),
    
]

goods/models.py
from django.db import models


class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Назва")
    slug = models.CharField(max_length=200, unique=True, blank=True, null=True, verbose_name="URL")

    class Meta:
        db_table = "category"
        verbose_name = "Категорію"
        verbose_name_plural = "Категорії"
        
    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Назва")
    slug = models.CharField(max_length=200, unique=True, blank=True, null=True, verbose_name="URL")
    description = models.TextField(blank=True, null=True, verbose_name="Описання")
    image = models.ImageField(upload_to="goods_images", blank=True, null=True, verbose_name="Фото")
    price = models.DecimalField(default=0.00, max_digits=10, decimal_places=2, verbose_name="Ціна")
    # discount = models.DecimalField(default=0.00, max_digits=4, decimal_places=2, verbose_name="Знижка в %")
    # quantity = models.PositiveIntegerField(default=0, verbose_name="Кількість")
    discount = models.DecimalField(default=0, max_digits=10, decimal_places=0, verbose_name="Площа")
    quantity = models.CharField(max_length=255, blank=True, verbose_name="Адреса")
    rooms = models.DecimalField(default=0, max_digits=10, decimal_places=0, verbose_name="Кімнати")
    contact_person = models.CharField(max_length=255, blank=True, verbose_name="Контактні дані") # Name of the contact person
    email = models.EmailField(max_length=254, blank=True, verbose_name="Email")  # Email address
    phone_number = models.CharField(max_length=20, blank=True, verbose_name="Номер телефону")  # Phone number
    booked_booking = models.BooleanField(max_length=150, default=False, verbose_name="Бронювання")
    # checkin = models.DateField(default='2024-01-01', verbose_name="Дата заїзду")  # Use verbose_name for Ukrainian translation
    # checkout = models.DateField(default='2024-01-01', verbose_name="Дата виїзду")  # Use verbose_name for Ukrainian translation
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name="Категорія")
      


    class Meta:
        db_table = "product"
        verbose_name = "Оголошення"
        verbose_name_plural = "Оголошення"
        ordering=("id",)
        
    def __str__(self):
        return f"{self.name} Кількість - {self.quantity}"
    
    def display_id(self):
        return f"{self.id:05}"
    
# class Booked(models.Model):  # Зміна на підкреслення
#     name = models.CharField(max_length=150, unique=True, verbose_name="І'мя")
#     email = models.EmailField(max_length=254, blank=True, verbose_name="Електронна пошта")  # Use verbose_name for Ukrainian translation
#     phone = models.CharField(max_length=20, blank=True, verbose_name="Телефон")  # Add phone number validation
#     checkin = models.DateField(default='2024-01-01', verbose_name="Дата заїзду")  # Use verbose_name for Ukrainian translation
#     checkout = models.DateField(default='2024-01-01', verbose_name="Дата виїзду")  # Use verbose_name for Ukrainian translation

#     class Meta:  # Зміна на підкреслення
#         db_table = "booked"  # Рядковий коментар
#         verbose_name = "Бронювання"  # Рядковий коментар
#         verbose_name_plural = "Бронювання"  # Рядковий коментар
#         ordering = ("id",)  # Рядковий коментар

#     def __str__(self):  # Зміна на підкреслення
#         return self.name

goods/forms.py
from django import forms

from goods.models import Products


class ProductForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = '__all__'
    
    # name = forms.CharField()
    # slug = forms.CharField()
    
# class BookedForm(forms.ModelForm):
#     class Meta:
#         model = Booked
#         fields = ('username', 'email', 'phone_number', 'checkin', 'checkout',)
    
#     username = forms.ImageField()
#     email = forms.CharField()
#     phone_number = forms.CharField()
#     checkin = forms.CharField()
#     checkout = forms.CharField()

goods/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.shortcuts import redirect, render
from django.template import context

from goods.forms import ProductForm
from goods.models import Products
from goods.utils import q_search

def catalog(request, category_slug=None):
    on_sale = request.GET.get('on_sale', None)
    order_by = request.GET.get('order_by', None)
    query = request.GET.get('q', None)
    rooms = request.GET.get('rooms', None)
    max_area = request.GET.get('max_area', None)
    min_price = request.GET.get('min_price', None)
    max_price = request.GET.get('max_price', None)
    
    if category_slug == 'all':
        goods = Products.objects.all()
    elif query:
        goods = q_search(query)
    else:
        goods = Products.objects.filter(category__slug=category_slug)
        
    if on_sale:
        goods = goods.filter(booked_booking=False)
    
    if rooms:
        goods = goods.filter(rooms=rooms)
        
    if max_area:
        goods = goods.filter(discount__lte=max_area)
        
    if min_price:
        goods = goods.filter(price__gte=min_price)

    if max_price:
        goods = goods.filter(price__lte=max_price)
        
    if order_by and order_by != 'default':
        goods = goods.order_by(order_by)
        
    context = {
        'title': 'Home - Каталог',
        'goods': goods,
        'slug_url': category_slug
    }
    return render(request, 'goods/catalog.html', context)

def product(request, product_slug):
    product = Products.objects.get(slug=product_slug)
    
    context = {
        'title': 'Home - Оголошення',
        'product': product
    }
        
    return render(request, 'goods/product.html', context=context)

goods/templates/goods/catalog.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="flex-container">
    <div class="row mt-1 position-fixed z-3">
        <div class="col-12 col-md-4 mb-2 position-fixed z-3">
            <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                Фільтри
            </button>

            <form action="{% if request.GET.q %}{% url "catalog:search" %}{% else %}{% url "catalog:index" slug_url %}{% endif %}" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on" {% if request.GET.on_sale == 'on' %}checked{% endif %}>
                    {% if request.GET.q %}
                        <input type="hidden" name="q" value="{{ request.GET.q }}">
                    {% endif %}
                    <label class="form-check-label" for="flexCheckDefault">
                        Вільні
                    </label>
                </div>

                <p class="text-white mx-3">Сортувати:</p>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" {% if not request.GET.order_by or request.GET.order_by == 'default' %}checked{% endif %}>
                    <label class="form-check-label" for="flexRadioDefault1">
                        За замовчуванням
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price" {% if request.GET.order_by == 'price' %}checked{% endif %}>
                    <label class="form-check-label" for="flexRadioDefault2">
                        Від дешевих до дорогих
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price" {% if request.GET.order_by == '-price' %}checked{% endif %}>
                    <label class="form-check-label" for="flexRadioDefault3">
                        Від дорогих до дешевих
                    </label>
                </div>
                
                <div class="form-group text-white mx-3 mt-1">
                    <label for="rooms" class="form-label">Кількість кімнат</label>
                    <input type="number" name="rooms" id="rooms" class="form-control form-control-sm" value="{{ request.GET.rooms|default_if_none:'' }}" style="width: 200px;">
                </div>

                <div class="form-group text-white mx-3 mt-1">
                    <label for="max_area" class="form-label">Максимальна площа (M²)</label>
                    <input type="number" name="max_area" id="max_area" class="form-control form-control-sm" value="{{ request.GET.max_area|default_if_none:'' }}" style="width: 200px;">
                </div>
                
                <p class="text-white mx-3 mt-1">Ціна:</p>
                <div class="form-group mx-3 mt-1 d-flex">
                    <label for="min_price" class="text-white mr-2">Від:</label>
                    <input type="number" name="min_price" id="min_price" class="form-control form-control-sm" value="{{ request.GET.min_price|default_if_none:'' }}" style="width: 100px;">
                    <label for="max_price" class="text-white mx-2">До:</label>
                    <input type="number" name="max_price" id="max_price" class="form-control form-control-sm" value="{{ request.GET.max_price|default_if_none:'' }}" style="width: 100px;">
                  </div>
                <button type="submit" class="btn btn-primary mx-3 mt-1">Примінити</button>
            </form>
        </div>
    </div>

    {% if request.GET.q %}
    <h3 class="mt-4">Результати пошуку за запитом {{ request.GET.q }}</h3>
    {% if not goods %}
        <h2 class="mt-4">За запитом нічого не знайдено</h2>
        <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
    {% endif %}
    {% endif %}

    {% for product in goods %}
    <section class="houses">
        <a href="{% url "catalog:product" product.slug %}" class="house">
            <div>
                {% if product.image %}
                    <img src="{{ product.image.url }}" alt="{{ product.name }}">
                {% else %}
                    <img src="{% static "deps/img/Not found image.png" %}" alt="...">
                {% endif %}
            </div>
            <div class="house-info">
                <h2>{% autoescape off %}
                    {% if product.headline %}
                    {{ product.headline|truncatechars:70 }}
                    {% else %}
                    {{ product.name|truncatechars:30 }}
                    {% endif %}
                {% endautoescape %}</h2>
                <p class="price">{{ product.price }}</p>
                <p class="product-id">id: {{ product.display_id }}; Кількість кімнат: {{ product.rooms }}</p>
            </div>
            <div class="description">
                <p>Опис:  {% autoescape off %}
                    {% if product.bodyline %}
                    {{ product.bodyline|truncatechars:80 }}
                    {% else %}
                    {{ product.description|truncatechars:50 }}
                    {% endif %}
                {% endautoescape %}</p>
            </div>
            <div class="address">
                <p>Розташування: 
                    {% autoescape off %}
                    {% if product.location %}
                    {{ product.location|truncatechars:80 }}
                    {% else %}
                    {{ product.quantity|truncatechars:80 }}
                    {% endif %}
                {% endautoescape %}; Площа: {{ product.discount }} M²</p>
            </div>
            <section class="catalog_booking">
                {% if product.booked_booking %}
                      <span class="booked">Заброньовано</span>
                {% endif %}
            </section>
        </a>
    </section>
    {% endfor %}
</div>
{% endblock %}

{% block footer %}
<footer><center>© 2024 Герчук Вікторія<br> 
    Всі права захищені.<br>
    м.Львів<br>
    Email: vikaherchyk@gmail.com</center>
</footer> 
{% endblock %}

goods/templates/goods/product.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="product-container">
    <div class="image-communication">
      <div class="product-image">
        <section>
          {% if product.booked_booking %}
                <span class="booked">Заброньовано</span>
          {% endif %}
          {% comment %} <span class="booked">{{product.booked_booking}}</span>
          <input type="hidden" id="booked_booking" value="{{ product.booked_booking }}"> {% endcomment %}
        </section>
        <img class="photo-image" src="{{product.image.url}}" alt="Product Image">
        <div class="information-house">
          <h2>{{product.name}}</h2>
          <p class="price">Адреса:{{product.quantity}}</br>
          {{product.price}}</br>
          Площа: {{product.discount}} M²</p>
          <p class="product-id">id: {{product.display_id}}</p>
          <p>Кількість кімнат: {{product.rooms}}</p>
        </div>
      </div>

      <div class="container-communication">
        <form method="post" class="form" id="bookingForm">
          {% csrf_token %}
          {% if request.GET.next %}
            <input type="hidden" name="next" value={{request.GET.next}}>
          {% endif %}
           <div class="form-control">
            <label for="id_username" class="form-label">Ім'я користувача*</label>
            <input type="text" class="form-control" id="id_username"
                value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                name="username"
                placeholder="Введіть ваше ім'я користувача" required>
                {% if form.username.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                {% endif %}
          </div>
          <div class="form-control">
            <label for="id_email" class="form-label">Email*</label>
            <input type="email" class="form-control" id="id_email"
                  value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                  name="email"
                  placeholder="Введіть ваш email" required>
                  {% if form.email.errors %}
                  <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                  {% endif %}
          </div>
          <div class="form-control">
            <label for="id_phone_number" class="form-label">Номер телефону*</label>
            <input type="tel" class="form-control" id="id_phone_number" 
            value="{% if form.phone_number.value %}{{ form.phone_number.value }}{% endif %}"
            name="phone_number"
            placeholder="Введіть номер телефону" required>
            {% if form.phone_number.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{form.phone_number.errors}}</div>
            {% endif %}
          </div>
          <div class="form-control">
            <label for="checkin" class="form-label">Дата заїзду:</label>
            <input type="date" class="form-control" id="checkin" name="checkin" required>
          </div>  
          <div class="form-control">
            <label for="checkout" class="form-label">Дата виїзду:</label>
            <input type="date" class="form-control" id="checkout" name="checkout" required>
          </div>

                        {% comment %} <div class="mb-3">
                            <label for="id_booked_booking" class="form-label">Заброньовано:</label>
                            <input type="checkbox" id="id_booked_booking" 
                              value="{% if form.booked_booking.value %}{{ form.booked_booking.value }}{% endif %}"
                              name="booked_booking">
                            {% if form.booked_booking.errors %}
                              <div class="alert alert-danger alert-dismissible fade show">{{form.booked_booking.errors}}</div>
                            {% endif %}
                        </div>
                        <button type="submit"
                        class="btn btn-primary booked-button">Бронювати</button> {% endcomment %}
          <button type="submit" name="book_button" class="btn btn-primary booked-button">Бронювати</button>



          <p>{{product.contact_person}}</p>
          <p>Email: {{product.email}}</p>
          Тел. <a href="tel: {{product.phone_number}}">{{product.phone_number}}</a>
        </form>
        
      </div>
    </div>
    <div class="information-house">
      <p class="product-description">ОПИС</p>
      <p class="text-description">{{product.description}}</p>
    </div>      
      
      {% comment %}
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2573.774501173837!2d24.068751199999998!3d49.827903299999996!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x473ac2b2c4f71cb3%3A0xdfcd6bfe20e6a086!2zNjJWLCDQstGD0LvQuNGG0Y8g0J_QsNGB0ZbRh9C90LAsIDYy0JIsINCb0YzQstC-0LIsINCb0YzQstC-0LLRgdC60LDRjyDQvtCx0LvQsNGB0YLRjCwgNzkwMDA!5e0!3m2!1suk!2sua!4v1714843088115!5m2!1suk!2sua" class="maps"></iframe>{% endcomment %}
</div>
{% endblock %}