app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),   
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
     path('user/', include('users.urls', namespace='user'))
]

if settings.DEBUG:
    urlpatterns += [
    path("__debug__/", include("debug_toolbar.urls")),  
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name='users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.cabinet, name='cabinet'), 
    path('announcement/', views.profile, name='profile'), 
    path('logout/', views.logout, name='logout'),    
]

goods/models.py
from django.db import models


class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Назва")
    slug = models.CharField(max_length=200, unique=True, blank=True, null=True, verbose_name="URL")

    class Meta:
        db_table = "category"
        verbose_name = "Категорію"
        verbose_name_plural = "Категорії"
        
    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Назва")
    slug = models.CharField(max_length=200, unique=True, blank=True, null=True, verbose_name="URL")
    description = models.TextField(blank=True, null=True, verbose_name="Описання")
    image = models.ImageField(upload_to="goods_images", blank=True, null=True, verbose_name="Фото")
    price = models.DecimalField(default=0.00, max_digits=10, decimal_places=2, verbose_name="Ціна")
    # discount = models.DecimalField(default=0.00, max_digits=4, decimal_places=2, verbose_name="Знижка в %")
    # quantity = models.PositiveIntegerField(default=0, verbose_name="Кількість")
    discount = models.DecimalField(default=0, max_digits=10, decimal_places=0, verbose_name="Площа")
    quantity = models.CharField(max_length=255, blank=True, verbose_name="Адреса")
    rooms = models.DecimalField(default=0, max_digits=10, decimal_places=0, verbose_name="Кімнати")
    contact_person = models.CharField(max_length=255, blank=True, verbose_name="Контактні дані") # Name of the contact person
    email = models.EmailField(max_length=254, blank=True, verbose_name="Email")  # Email address
    phone_number = models.CharField(max_length=20, blank=True, verbose_name="Номер телефону")  # Phone number
    booked_booking = models.BooleanField(max_length=150, default=False, verbose_name="Бронювання")
    # checkin = models.DateField(default='2024-01-01', verbose_name="Дата заїзду")  # Use verbose_name for Ukrainian translation
    # checkout = models.DateField(default='2024-01-01', verbose_name="Дата виїзду")  # Use verbose_name for Ukrainian translation
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name="Категорія")
      


    class Meta:
        db_table = "product"
        verbose_name = "Оголошення"
        verbose_name_plural = "Оголошення"
        ordering=("id",)
        
    def __str__(self):
        return f"{self.name} Кількість - {self.quantity}"
    
    def display_id(self):
        return f"{self.id:05}"
    
# class Booked(models.Model):  # Зміна на підкреслення
#     name = models.CharField(max_length=150, unique=True, verbose_name="І'мя")
#     email = models.EmailField(max_length=254, blank=True, verbose_name="Електронна пошта")  # Use verbose_name for Ukrainian translation
#     phone = models.CharField(max_length=20, blank=True, verbose_name="Телефон")  # Add phone number validation
#     checkin = models.DateField(default='2024-01-01', verbose_name="Дата заїзду")  # Use verbose_name for Ukrainian translation
#     checkout = models.DateField(default='2024-01-01', verbose_name="Дата виїзду")  # Use verbose_name for Ukrainian translation

#     class Meta:  # Зміна на підкреслення
#         db_table = "booked"  # Рядковий коментар
#         verbose_name = "Бронювання"  # Рядковий коментар
#         verbose_name_plural = "Бронювання"  # Рядковий коментар
#         ordering = ("id",)  # Рядковий коментар

#     def __str__(self):  # Зміна на підкреслення
#         return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')
    
    class Meta:
        db_table = 'user'
        verbose_name = 'Користувача'
        verbose_name_plural = 'Користувачі'

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    
    class Meta:
        model = User
        fields = ['username', 'password']
        
    username = forms.CharField()
    password = forms.CharField()
        
    # username = forms.CharField(
    #     label="Ім'я",
    #     widget=forms.TextInput(attrs={"autofocus": True,
    #                                   'class': 'form-control',
    #                                   'placeholder': 'Введите ваше имя пользователя'})
    # )
    # password = forms.CharField(
    #     label="Пароль",
    #     widget=forms.PasswordInput(attrs={"autocomplete": "current-password",
    #                                     'class': 'form-control',
    #                                     'placeholder': 'Введите ваш пароль'})
    # )
    
class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )
    
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

        
    # first_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введите ваше имя",
    #         }
    #     )
    # )
    # last_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введите вашу фамилию",
    #         }
    #     )
    # )
    # username = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введите ваше имя пользователя",
    #         }
    #     )
    # )
    # email = forms.CharField(
    #     widget=forms.EmailInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введите ваш email *youremail@example.com",
    #         }
    #     )
    # )
    # password1 = forms.CharField(
    #     widget=forms.PasswordInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введите ваш пароль",
    #         }
    #     )
    # )
    # password2 = forms.CharField(
    #     widget=forms.PasswordInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Поддтвердите ваш пароль",
    #         }
    #     )
    # )
    
class CabinetForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "username",
            "email",)

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

users/views.py
from django.contrib.auth.decorators import login_required
from audioop import reverse
from django.contrib import auth, messages
from django.shortcuts import redirect, render

from goods.forms import ProductForm
from users.forms import CabinetForm, UserLoginForm, UserRegistrationForm


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            if user:
                auth.login(request, user)
                messages.success(request, f"{username}, Ви увійшли до облікового запису")
                
                if request.POST.get('next', None):
                        return redirect(request.POST.get('next'))
                    
                return redirect('main:index')
    else:
        form = UserLoginForm()

    context = {
        'title': 'Home - Авторизація',
        'form': form
    }
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()


            user = form.instance
            auth.login(request, user)
            messages.success(request, f"{user.username}, Ви успішно зареєстровані та увійшли до облікового запису")
            return redirect('main:index')
    else:
        form = UserRegistrationForm()
    
    context = {
        'title': 'Home - Реєстрація',
        'form': form
    }
    return render(request, 'users/registration.html', context)

@login_required
def profile(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)  # Handle file uploads
        if form.is_valid():
            form.save()  # Save the form data to the database
            messages.success(request, "Оголошення успішно додано")
            return redirect('main:index')  # Redirect to success page (replace with your URL name)
    else:
        form = ProductForm()

    context = {
        'title': 'Home - Додати оголошення',
        'form': form
        }
    return render(request, 'users/profile.html', context)

@login_required
def cabinet(request):
    if request.method == 'POST':
        form = CabinetForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Профайл успішно оновлено")
            return redirect('user:cabinet')
    else:
        form = CabinetForm(instance=request.user)

    # orders = Order.objects.filter(user=request.user).prefetch_related(
    #             Prefetch(
    #                 "orderitem_set",
    #                 queryset=OrderItem.objects.select_related("product"),
    #             )
    #         ).order_by("-id")
        

    context = {
        'title': 'Home - Профіль',
        'form': form,
        # 'orders': orders,
    }
    return render(request, 'users/cabinet.html', context)

@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, Ви вийшли з облікового запису")
    auth.logout(request)
    return redirect('main:index')

users/templates/users/cabinet.html
{% extends "base.html" %}
{% load static %}
{% comment %} {% load carts_tags %} {% endcomment %}

{% block content %}
<div class="bg-white p-3 mx-auto rounded custom-shadow">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <!-- Профіль з даними користувача -->
            <div class="col-md-5 mx-auto">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Профіль користувача</h3>
                    <form action="{% url "users:cabinet" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12 mb-3 text-center">
                                {% if user.image %}
                                    <img src="{{ user.image.url }}"
                                        alt="Аватар користувача" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                {% else %}
                                    <img src="{% static "deps/img/baseavatar.jpg" %}"
                                        alt="Аватар користувача" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                {% endif %}
                                <input type="file" class="form-control mt-3" id="id_image"
                                    name='image'
                                    accept="image/*">
                                    {% if form.image.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_first_name" class="form-label">Ім'я*</label>
                                <input type="text" class="form-control" id="id_first_name"
                                    name="first_name"
                                    placeholder="Введіть ваше ім'я"
                                    value="{{ form.first_name.value }}"
                                    required>
                                    {% if form.first_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_last_name" class="form-label">Прізвище*</label>
                                <input type="text" class="form-control" id="id_last_name"
                                    name="last_name"
                                    placeholder="Введіть ваше прізвище"
                                    value="{{ form.last_name.value }}"
                                    required>
                                    {% if form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_username" class="form-label">Ім'я користувача*</label>
                                <input type="text" class="form-control" id="id_username"
                                    name="username"
                                    placeholder="Введіть ваше ім'я користувача"
                                    value="{{ form.username.value }}"
                                    required>
                                    {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                    {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                    name="email"
                                    placeholder="Введіть ваш email *youremail@example.com"
                                    value="{{ form.email.value }}"
                                    required>
                                    {% if form.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                    {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Зберегти</button>
                    </form>
                </div>
            </div>            
        </div>
    </div>
</div>
{% endblock  %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- Контент на сторінці -->
<div class="bg-white p-3 mx-auto rounded custom-shadow">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Додати оголошення</h2>
                <form action="{% url "user:profile" %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_name" class="form-label">Назва:</label>
                            <input type="text" class="form-control" id="id_name" 
                                value="{% if form.name.value %}{{ form.name.value }}{% endif %}"
                                name="name"
                                placeholder="Введіть назву" required>
                                {% if form.name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.name.errors}}</div>
                                {% endif %}
                        </div>
                        
                        <div class="col-md-6 mb-3">
                            <label for="id_slug" class="form-label">URL:</label>
                            <input type="text" class="form-control" id="id_slug"
                                value="{% if form.slug.value %}{{ form.slug.value }}{% endif %}"
                                name="slug"
                                placeholder="kvartiri-z-meblyami" required>
                                {% if form.slug.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.slug.errors}}</div>
                                {% endif %}
                        </div>
            
                        <div class="mb-3">
                            <label for="id_description" class="form-label">Опис:</label>
                            <textarea class="form-control" id="id_description" 
                                value="{% if form.description.value %}{{ form.description.value }}{% endif %}"
                                name="description" rows="3"></textarea>
                                {% if form.description.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.description.errors}}</div>
                                {% endif %}
                        </div>
            
                        <div class="mb-3">
                            <label for="id_image" class="form-label">Фото:</label>
                            <input type="file" class="form-control" id="id_image"
                                value="{% if form.image.value %}{{ form.image.value }}{% endif %}"
                                name="image">
                                {% if form.image.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
                                {% endif %}
                        </div>
            
                        <div class="mb-3">
                            <label for="id_price" class="form-label">Ціна:</label>
                            <input type="number" class="form-control" id="id_price"
                                value="{% if form.price.value %}{{ form.price.value }}{% endif %}"
                                name="price" step="100" required>
                                {% if form.price.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.price.errors}}</div>
                                {% endif %}
                        </div>
            
                        <div class="mb-3">
                            <label for="id_discount" class="form-label">Площа:</label>
                            <input type="number" class="form-control" id="id_discount"
                              value="{% if form.discount.value %}{{ form.discount.value }}{% endif %}"
                              name="discount"
                              placeholder="M²" step="10">
                            {% if form.discount.errors %}
                              <div class="alert alert-danger alert-dismissible fade show">{{form.discount.errors}}</div>
                            {% endif %}
                        </div>
            
                        <div class="mb-3">
                            <label for="id_quantity" class="form-label">Адрес:</label>
                            <input type="text" class="form-control" id="id_quantity" 
                              value="{% if form.quantity.value %}{{ form.quantity.value }}{% endif %}"
                              name="quantity"
                              placeholder="Введіть адресу" required>
                            {% if form.quantity.errors %}
                              <div class="alert alert-danger alert-dismissible fade show">{{form.quantity.errors}}</div>
                            {% endif %}
                        </div>
                        {% comment %} <div class="mb-3">
                            <label for="id_booked_booking" class="form-label">Заброньовано:</label>
                            <input type="checkbox" id="id_booked_booking" 
                              value="{% if form.booked_booking.value %}{{ form.booked_booking.value }}{% endif %}"
                              name="booked_booking">
                            {% if form.booked_booking.errors %}
                              <div class="alert alert-danger alert-dismissible fade show">{{form.booked_booking.errors}}</div>
                            {% endif %}
                        </div> {% endcomment %}

                        <div class="mb-3">
                            <label for="id_rooms" class="form-label">Кількість кімнат:</label>
                            <input type="number" class="form-control" id="id_rooms"
                                value="{% if form.rooms.value %}{{ form.rooms.value }}{% endif %}"
                                name="rooms" step="1" required>
                                {% if form.rooms.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.rooms.errors}}</div>
                                {% endif %}
                        </div>

                        <div class="mb-3">
                            <label for="id_category" class="form-label">Категорія:</label>
                            <select class="form-select" id="id_category" name="category" required>
                                <option value="">--- Виберіть категорію ---</option>
                                {% for category in categories %}
                                    <option value="{{ category.pk }}">{{ category.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <h3 class="mt-5">Ваші контактні дані</h3>
                        <div class="col-md-6 mb-3">
                            <label for="id_contact_person" class="form-label">Контактна особа*</label>
                            <input type="text" class="form-control" id="id_contact_person" 
                            value="{% if form.contact_person.value %}{{ form.contact_person.value }}{% endif %}"
                            name="contact_person"
                            placeholder="Введіть ім'я та прізвище" required>
                            {% if form.contact_person.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.contact_person.errors}}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Email-адреса*</label>
                            <input type="email" class="form-control" id="id_email" 
                            value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                            name="email"
                            placeholder="Введіть email" required>
                            {% if form.email.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_phone_number" class="form-label">Номер телефону*</label>
                            <input type="tel" class="form-control" id="id_phone_number" 
                            value="{% if form.phone_number.value %}{{ form.phone_number.value }}{% endif %}"
                            name="phone_number"
                            placeholder="Введіть номер телефону" required>
                            {% if form.phone_number.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.phone_number.errors}}</div>
                            {% endif %}
                        </div>



                    </div>
                    <button type="submit"
                        class="btn btn-dark btn-block">Додати оголошення</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- Контент на сторінці -->
<div class="bg-white p-3 mx-auto rounded custom-shadow">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Реєстрація</h2>
                <form action="{% url "user:registration" %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Ім'я*</label>
                            <input type="text" class="form-control" id="id_first_name"
                                value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                name="first_name"
                                placeholder="Введіть ваше ім'я" required>
                                {% if form.first_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Прізвище*</label>
                            <input type="text" class="form-control" id="id_last_name"
                                value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                name="last_name"
                                placeholder="Введіть ваше прізвище" required>
                                {% if form.last_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_username" class="form-label">Ім'я користувача*</label>
                            <input type="text" class="form-control" id="id_username"
                                value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                name="username"
                                placeholder="Введіть ваше ім'я користувача" required>
                                {% if form.username.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Email*</label>
                            <input type="email" class="form-control" id="id_email"
                                value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                name="email"
                                placeholder="Введіть ваш email" required>
                                {% if form.email.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password1" class="form-label">Пароль*</label>
                            <input type="password" class="form-control" id="id_password1"
                                value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                                name="password1"
                                placeholder="Введіть пароль" required>
                                {% if form.password1.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password2" class="form-label">Підтвердження пароля*</label>
                            <input type="password" class="form-control" id="id_password2"
                                value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                                name="password2"
                                placeholder="Підтвердіть пароль" required>
                                {% if form.password2.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
                                {% endif %}
                        </div>
                    </div>
                    <button type="submit"
                        class="btn btn-dark btn-block">Зареєструватись</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}