app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),   
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
     path('user/', include('users.urls', namespace='user'))
]

if settings.DEBUG:
    urlpatterns += [
    path("__debug__/", include("debug_toolbar.urls")),  
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import include, path
# from .views import booking
# from .views import update_booking
from goods import views

app_name='goods'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),
    # path('booking/<int:product_id>/', booking, name='booking'),
    # path('booking/update/<int:display_id>/', update_booking, name='update_booking'),
    # path('update-booking/', update_booking, name='update_booking_url'),
    
]

main/urls.py
from django.urls import path

from main import views

app_name='main'

urlpatterns = [
    path('', views.index, name='index'),
    
]

users/urls.py
from django.urls import path

from users import views

app_name='users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.cabinet, name='cabinet'), 
    path('announcement/', views.profile, name='profile'), 
    path('logout/', views.logout, name='logout'),    
]

templates/base.html
{% load static %}
{% load goods_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/photo.jpg" %}">
    <title>{{ title }}</title>
    <!-- Ваша таблиця стилів (CSS) або інші метадані -->
    <link rel="stylesheet" href="{% static "deps/css/styles_form.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/style.css" %}">
	<link rel="stylesheet" href="{% static "deps/css/styles_apartments.css"%}">
    <link rel="stylesheet" href="{% static "deps/css/gallery.css"%}">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url "main:index" %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link  text-white" href="{% url "user:login" %}">Увійти/Зареєструватися</a>
                            </li>
                        {% else %}
                            <li class="nav-item dropdown ">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    Мій профіль
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item  text-white" href="{% url "user:cabinet" %}">Профіль</a>
                                    </li>
                                    <li><a class="dropdown-item  text-white" href="{% url "user:profile" %}">Додати оголошення</a>
                                    </li>
                                    {% if user.is_admin or user.is_staff %}
                                        <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Адмін панель</a></li>
                                    {% endif %}
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item  text-white" href="{% url "user:logout" %}">Вийти</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                    <div class="dropdown mb-2" style="margin: 0 auto;">
                        <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Каталог
                            <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16"
                                height="16">
                        </button>
                        <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                            {% tag_categories as categories %}
                            {% for category in categories %}
                                <li><a class="dropdown-item text-white" href="{% url "catalog:index" category.slug %}">{{category.name}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% comment %} <div>
                        <li><a class="dropdown-item  text-white" href="{% url "goods:booking" %}">Бронювання</a>
                        </li>
                    </div> {% endcomment %}
                    <form class="d-flex" role="search" action="{% url "catalog:search" %}" method="get">
                        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Пошук</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>


    {% comment %} <header>
        <h1 class="logo">Назва</h1>
        <form class='input-search' role="search" action="{% url "catalog:search" %}" method="get">
            <input type="search" name="q" placeholder="Search" aria-label="Search">
            <button class="button-search" type="submit">Пошук</button>
        </form>
        <nav class="navigation">
            <a href="{% url "main:index" %}">Головна</a>
            {% tag_categories as categories %}
            {% for category in categories %}
            <a href="{% url "catalog:index" category.slug %}">{{category.name}}</a>
            {% endfor %}
            {% if not user.is_authenticated %}
                <a href="{% url "user:login" %}">Увійти/Зареєструватися</a>
            {% else %}
                <a href="{% url "user:profile" %}">Додати оголошення</a>
                {% if user.is_admin or user.is_staff %}
                <a href="{% url "admin:index" %}">Адмін панель</a>
                {% endif %}
                <a href="{% url "user:logout" %}">Вийти</a>
            {% endif %}
            <!--<button class="btnLogin-popup">Увійти/Зареєструватися</button>-->
        </nav>
    </header> {% endcomment %}

    <!--<div class="wrapper">
        <span class="icon-close">
            <ion-icon name="close"></ion-icon>
        </span>
        <div class="from-box login">
            <h2>Увійти</h2>
            <form action="#" method="post">
                <div class="input-box">
                    <span class="icon"><ion-icon name="mail"></ion-icon></span>
                    <input type="email" required>
                    <label>Email</label>
                </div>
                <div class="input-box">
                    <span class="icon"><ion-icon name="lock-closed"></ion-icon></span>
                    <input type="password" required>
                    <label>Пароль</label>
                </div>
                <div class="remember-forgot">
                    <label><input type="checkbox">Пам'ятай мене</label>
                    <a href="#">Забули пароль?</a>
                </div>
                <button type="submit" class="btn">Увійти</button>
                <div class="login-register">
                    <p>Немає облікового запису?<a href="#" class="register-link">Зареєструватися</a></p>
                </div>
            </form>
        </div>

        <div class="from-box register">
            <h2>Зареєструватися</h2>
            <form action="#">
                <div class="input-box">
                    <span class="icon"><ion-icon name="person"></ion-icon></span>
                    <input type="text" required>
                    <label>Ім'я</label>
                </div>
                <div class="input-box">
                    <span class="icon"><ion-icon name="mail"></ion-icon></span>
                    <input type="email" required>
                    <label>Email</label>
                </div>
                <div class="input-box">
                    <span class="icon"><ion-icon name="lock-closed"></ion-icon></span>
                    <input type="password" required>
                    <label>Пароль</label>
                </div>
                <div class="remember-forgot">
                    <label><input type="checkbox">Я погоджуюся з положеннями та умовами</label>
                </div>
                <button type="submit" class="btn">Зареєструватися</button>
                <div class="login-register">
                    <p>Вже є аккаунт?<a href="#" class="login-link">Увійти</a></p>
                </div>
            </form>
        </div>
    </div>-->
    {% include "includes/notifications.html" %}
    <main> 
        {% comment %} id="container" {% endcomment %}
        
        {% block content %}
        {% endblock%}

    </main>
    
    {% block footer %}
    {% endblock %} 

    <!-- Ваші скрипти чи інші ресурси -->
    <script src="{% static "deps/js/script_form.js" %}"></script>
    <script src="{% static "deps/js/gallery.js"%}"></script>
    <script src="{% static "deps/js/script.js"%}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/jquery-events.js" %}"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</body>
</html>